apiVersion: apps/v1
kind: DaemonSet
metadata:
    name: elasticsearch
spec:
    selector:
        matchLabels:
            app: 
    template: 
        metadata:
            labels:
                app: monitoring-agent
        spec: 
            containers:
                - name: monitoring-agent
                  image: monitoring-agent